// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO6P1ZHxmwghnccTQNuuJeN6HoplbB8wo',
    appId: '1:729664820275:web:ea79604df1011c9ec73f46',
    messagingSenderId: '729664820275',
    projectId: 'qrcodetestes',
    authDomain: 'qrcodetestes.firebaseapp.com',
    storageBucket: 'qrcodetestes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_uqIiuhcCR5eKb_GYZr8K5GlASE9T_mY',
    appId: '1:729664820275:android:e6ae23604f9c6bc3c73f46',
    messagingSenderId: '729664820275',
    projectId: 'qrcodetestes',
    storageBucket: 'qrcodetestes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl1YLy_mPFgvxbxEjA0gREdocVqR4bL5M',
    appId: '1:729664820275:ios:bea01a67ff73f53cc73f46',
    messagingSenderId: '729664820275',
    projectId: 'qrcodetestes',
    storageBucket: 'qrcodetestes.appspot.com',
    iosBundleId: 'com.kuldiiproject.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl1YLy_mPFgvxbxEjA0gREdocVqR4bL5M',
    appId: '1:729664820275:ios:bea01a67ff73f53cc73f46',
    messagingSenderId: '729664820275',
    projectId: 'qrcodetestes',
    storageBucket: 'qrcodetestes.appspot.com',
    iosBundleId: 'com.kuldiiproject.qrCode',
  );
}
